# generated by datamodel-codegen:
#   filename:  swagger.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Odds(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    home: Annotated[float | None, Field(examples=[2.45])] = None
    draw: Annotated[float | None, Field(examples=[3.1])] = None
    away: Annotated[float | None, Field(examples=[2.8])] = None


class Balance(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    balance: Annotated[float | None, Field(examples=[125.5])] = None
    currency: Annotated[str | None, Field(examples=['EUR'])] = None


class Selection(StrEnum):
    home = 'HOME'
    draw = 'DRAW'
    away = 'AWAY'


class PlaceBetRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    match_id: Annotated[
        str, Field(alias='matchId', examples=['premier-league-manutd-chelsea'])
    ]
    selection: Annotated[Selection, Field(examples=['HOME'])]
    stake: Annotated[float, Field(examples=[10], ge=1.0, le=100.0)]


class PlaceBetResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: Annotated[str | None, Field(examples=['Bet placed successfully'])] = None
    match_id: Annotated[
        str | None, Field(alias='matchId', examples=['premier-league-manutd-chelsea'])
    ] = None
    selection: Annotated[str | None, Field(examples=['HOME'])] = None
    stake: Annotated[float | None, Field(examples=[10])] = None
    odds: Annotated[float | None, Field(examples=[2.45])] = None
    payout: Annotated[float | None, Field(examples=[24.5])] = None
    balance: Annotated[float | None, Field(examples=[115.5])] = None
    currency: Annotated[str | None, Field(examples=['EUR'])] = None


class Error(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: Annotated[str | None, Field(examples=['insufficient_balance'])] = None
    message: Annotated[str | None, Field(examples=['Insufficient balance'])] = None


class Error1(StrEnum):
    missing_user_id = 'missing_user_id'
    invalid_user_id = 'invalid_user_id'


class AuthError(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: Annotated[Error1 | None, Field(examples=['missing_user_id'])] = None


class Match(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(examples=['premier-league-manutd-chelsea'])] = None
    competition: Annotated[str | None, Field(examples=['Premier League'])] = None
    kickoff_date: Annotated[
        date | None, Field(alias='kickoffDate', examples=['2026-01-30'])
    ] = None
    home_team: Annotated[
        str | None, Field(alias='homeTeam', examples=['Manchester Utd'])
    ] = None
    away_team: Annotated[str | None, Field(alias='awayTeam', examples=['Chelsea'])] = (
        None
    )
    odds: Odds | None = None
